services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_DB: ${POSTGRES_DBNAME:-booking_app}
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  booking_api:
    build: ./django
    restart: always
    # sleep some seconds becuase django fails if db container aren't ready yet.
    # This is especially true on our pi server.
    # Should be fixed in python code rather than here if possible.
    command: bash -c "sleep ${DJANGO_DELAY:-3} && python manage.py migrate && python manage.py runserver 0.0.0.0:8000" 
    depends_on:
      - db
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-db}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DBNAME: ${POSTGRES_DBNAME:-booking_app}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
    ports:
      - 8001:8000
      