services:
  db:
    image: postgres:15
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/postgresql/data

    restart: always
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  booking_api:
    build: ./django/
    restart: always
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./django
        target: /usr/src/app
    ports:
      - 8000:8000

  bio_app:
    build: ./bio-app/
    restart: always
    depends_on:
      - booking_api
    volumes:
      #- type: bind
      #  source: ./bio-app
      #  target: /usr/src/app
      - ./bio-app:/usr/src/app
      - exclude:/usr/src/app/node_modules/
    ports:
      - 3000:3000

volumes:
  db_data:
  exclude:
    # https://www.baeldung.com/ops/docker-exclude-sub-folder-when-adding-volume
    driver: local
