services:
  db:
    image: postgres:15
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/postgresql/data

    restart: always
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  booking_api:
    build: ./django/
    volumes:
      - ./django:/usr/src/app
    restart: always
    depends_on:
      - db
    environment:
      DJANGO_DELAY: ${DJANGO_DELAY:-3}
      POSTGRES_HOST: ${POSTGRES_HOST:-db}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DBNAME: ${POSTGRES_DBNAME:-booking_app}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME:-admin}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL:-admin@example.com}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD:-admin}
    ports:
      - 8000:8000

  bio_app:
    restart: always
    depends_on:
      - booking_api

volumes:
  db_data:
  exclude:
    # https://www.baeldung.com/ops/docker-exclude-sub-folder-when-adding-volume
    driver: local
